networks:
  inside:
    external: false

services:
  db:
    image: mariadb:lts-ubi
#    env_file:
#      - .env
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${OJS_DB_NAME:-ojs}"
      MYSQL_USER: "${OJS_DB_USER:-ojs}"
      MYSQL_PASSWORD: "${OJS_DB_PASSWORD:-ojsPwd}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/docker-entrypoint-initdb.d
#      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
    networks:
      - inside
    restart: unless-stopped

  ojs:
    image: "pkpofficial/${OJS_IMAGE:-ojs}:${OJS_VERSION:-latest}"
#    env_file:
#      - .env
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
#      - ./volumes/logs/app:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
      - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
    restart: unless-stopped
